repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
        exclude: tests/test_files/Mapper/test_error.json
      - id: check-merge-conflict
        files: \.py$
      - id: debug-statements
        language_version: python3
        files: \.py$
      - id: end-of-file-fixer
        files: \.py$
      - id: mixed-line-ending
      - id: pretty-format-json
        args: ['--autofix', ]
        exclude: tests/test_files/Mapper/test_error.json
      - id: trailing-whitespace
        files: \.py$

    - repo: https://github.com/PyCQA/bandit
      rev: 1.7.3
      hooks:
      - id: bandit
        language_version: python3
        exclude: (^tests/|^tools/)
        args:
        - --recursive
        - --skip
        - B110,B112,B311,B410
        - thug

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.1.13
      hooks:
        # Run the linter.
        - id: ruff
        # Run the formatter.
        - id: ruff-format
